project:
  type: website
  output-dir: docs

website:
  title: "R en Rosario - Charla 1/9/23"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: preparacion.qmd
        text: "Preparación y materiales"
      - href: presentacion_ropensci.qmd
        text: "Sobre ROpenSci"
      - href: about.qmd
        text: "Creando paquetes multilingües"
      - href: crear_paquetes.qmd
        text: "Más detalles"

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

